# Nombre de la aplicacion
spring.application.name=UrbanPulse

# Configuracion JSP
# TODO: Seguramente usemos React y JS
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

# Conexion a la base de datos (PostgreSQL / Supabase)

# Para usar la BD REMOTA:
# 1. Comentar las 3 lineas del bloque LOCAL.
# 2. Descomentar las 3 lineas del bloque REMOTO.

# BD LOCAL (Supabase via Docker)
spring.datasource.url=jdbc:postgresql://127.0.0.1:54322/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# BD REMOTA (credenciales en .env)
#spring.datasource.url=${POSTGRES_URL}
#spring.datasource.username=${POSTGRES_USER}
#spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
