package urbanpulse.service;

import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;
import urbanpulse.dao.IncidentRepository;
import urbanpulse.dto.Incident;
import urbanpulse.mapper.IncidentMapper;

@Service
@AllArgsConstructor
public class IncidentService {
    private final IncidentRepository incidentRepository;
    private final IncidentMapper incidentMapper;

    /*
     * Saves a new incident. The status always starts as REPORTED and
     * id and timestamps are generated by the persistence layer.
     */
    public Incident addIncident(Incident incident) {
        return incidentMapper.toDTO(incidentRepository.save(incidentMapper.toEntity(incident)));
    }

}
