package urbanpulse.dto;

public enum Category {
    STREET_LIGHTING, TRAFFIC_LIGHTS, ROAD_SIGNS, ROADS_AND_SIDEWALKS, STREET_FURNITURE,
    WASTE_CONTAINERS, STREET_CLEANING, TREES, GREEN_AREAS, WATER_AND_FOUNTAINS, PUBLIC_TRANSPORT, OTHER
}
