package urbanpulse.dto;

public enum District {
    CENTRO, ESTE, CIUDAD_JARDIN, BAILEN_MIRAFLORES, PALMA_PALMILLA, CRUZ_DE_HUMILLADERO,
    CARRETERA_DE_CADIZ, CHURRIANA, CAMPANILLAS, PUERTO_DE_LA_TORRE, TEATINOS_UNIVERSIDAD
}
